codestates-seb/seb44_main_005

server/src/main/java/actiOn/auth/jwt/TokenProvider.java
server/src/main/java/actiOn/config/SecurityConfiguration.java
server/src/main/java/actiOn/member/entity/Member.java
server/src/main/java/actiOn/store/entity/Store.java

[Backend] 엔티티 수정

---

server/src/main/java/actiOn/wish/controller/WishController.java
server/src/main/java/actiOn/wish/mapper/WishMapper.java
server/src/main/java/actiOn/wish/service/WishService.java

- resolved #12
- resolved
화이팅!!!

[feat] wish controller 작성 (#14)

---

server/src/main/java/actiOn/review/controller/ReviewController.java
server/src/main/java/actiOn/review/mapper/ReviewMapper.java
server/src/main/java/actiOn/review/service/ReviewService.java

- resolved #12
- resolved
화이팅!!!

[feat] review controller 작성 (#9)

---

.gitignore
server/src/main/java/actiOn/Img/profileImg/ProfileImgDto.java
server/src/main/java/actiOn/member/controller/MemberController.java
server/src/main/java/actiOn/member/dto/MemberDto.java
server/src/main/java/actiOn/member/service/MemberService.java

[Backend] 회원 컨트롤러 구현

---

server/src/main/java/actiOn/store/controller/StoreController.java
server/src/main/java/actiOn/store/service/StoreService.java

[Backend] store 컨트롤러 구현

---

server/src/main/java/actiOn/ActiOnApplication.java
server/src/main/java/actiOn/business/entity/Business.java
server/src/main/java/actiOn/helper/audit/BaseEntity.java
server/src/main/java/actiOn/helper/validator/NotSpace.java
server/src/main/java/actiOn/helper/validator/NotSpaceValidator.java
server/src/main/java/actiOn/member/entity/Member.java
server/src/main/java/actiOn/reservation/entity/Reservation.java
server/src/main/java/actiOn/reservation/entity/ReservationItem.java
server/src/main/java/actiOn/review/entity/Review.java
server/src/main/java/actiOn/store/entity/Store.java

[Backend] validator추가 및 패키지 정리

---

server/build.gradle
server/src/main/java/actiOn/Img/profileImg/ProfileImgRepository.java
server/src/main/java/actiOn/Img/service/ImgService.java
server/src/main/java/actiOn/Img/storeImg/StoreImgRepository.java
server/src/main/java/actiOn/config/SecurityConfiguration.java
server/src/main/java/actiOn/helper/audit/BaseEntity.java
server/src/main/java/actiOn/map/response/GeoLocation.java
server/src/main/java/actiOn/map/response/KakaoMapResponse.java
server/src/main/java/actiOn/map/service/KakaoMapService.java
server/src/main/java/actiOn/store/controller/StoreController.java
server/src/main/java/actiOn/store/dto/StorePatchDto.java
server/src/main/java/actiOn/store/dto/StorePostDto.java
server/src/main/java/actiOn/store/dto/StoreResponseDto.java
server/src/main/java/actiOn/store/entity/Store.java
server/src/main/java/actiOn/store/mapper/StoreMapper.java
server/src/main/java/actiOn/store/service/StoreService.java
server/src/main/resources/application.yml

- resolved #5 
- resolved
화이팅!!!

feat/be/reservation 카카오맵 연동 / store 기능구현 (#5)

---

server/src/main/java/actiOn/Img/service/ImgService.java
server/src/main/java/actiOn/store/controller/StoreController.java
server/src/main/java/actiOn/store/dto/StorePostDto.java

- resolved #5 
- resolved
화이팅!!!

feat/be/image 이미지 업로드 로직 최적화 (#5)

---

server/appspec.yml
server/buildspec.yml
server/scripts/initialize.sh
server/scripts/server_clear.sh
server/scripts/server_start.sh
server/scripts/server_stop.sh

[Backend] add Auto Deployment

---

client/src/components/Footer/Footer.tsx
client/src/components/Layout/FooterLayout.tsx
client/src/pages/Register.tsx
client/src/router/CategoryRouter.tsx
client/src/router/MainRouter.tsx
client/src/styles/Footer/Footer.ts

[feat] 푸터 구현 완료

---

client/src/pages/Login.tsx
client/src/pages/Register.tsx
client/src/styles/Button/Button.ts
client/src/styles/Login/Login.ts
client/src/styles/Register/Register.ts

- resolved #50 
- 로그인 border도 회원가입이랑 통일시켰습니다.
화이팅!!!

[Frontend] 회원가입 페이지 구현

---

server/src/main/java/actiOn/auth/oauth2/OAuth2MemberSuccessHandler.java
server/src/main/java/actiOn/config/SecurityConfiguration.java
server/src/main/java/actiOn/member/entity/Member.java
server/src/main/java/actiOn/member/service/MemberService.java

[Backend] Oauth2 구글 로그인 기능

---

server/src/main/java/actiOn/Img/service/ImgService.java
server/src/main/java/actiOn/auth/utils/AuthUtil.java
server/src/main/java/actiOn/exception/ExceptionCode.java
server/src/main/java/actiOn/member/controller/MemberController.java
server/src/main/java/actiOn/member/dto/MemberResponseDto.java
server/src/main/java/actiOn/member/entity/Member.java
server/src/main/java/actiOn/member/mapper/MemberMapper.java
server/src/main/java/actiOn/member/service/MemberService.java

[Backend] Member 구현 (일부)

---

client/.env
client/.eslintrc
client/src/App.tsx
client/src/components/Button/Button.tsx
client/src/components/CategoryDetail/PaymentInfo.tsx
client/src/components/Header/Dropdown.tsx
client/src/components/Header/Header.tsx
client/src/components/Header/Searchbar.tsx
client/src/components/Home/Carousel.tsx
client/src/components/Layout/CategoryLayout.tsx
client/src/components/Layout/FooterLayout.tsx
client/src/dummy/categorydetail.ts
client/src/dummy/mypage.ts
client/src/dummy/reservation.ts
client/src/pages/CategoryPage.tsx
client/src/pages/Home.tsx
client/src/pages/Login.tsx
client/src/pages/MyPage.tsx
client/src/pages/Partner.tsx
client/src/pages/Register.tsx
client/src/pages/ReservationCheck.tsx
client/src/pages/ReservationModify.tsx
client/src/pages/StoreAdd.tsx
client/src/pages/StoreCheck.tsx
client/src/pages/StoreModify.tsx
client/src/pages/Welcome.tsx
client/src/pages/WishList.tsx
client/src/router/MyRouter.tsx
client/src/styles/Register/Register.ts
client/src/styles/Reservation/ReservationModify.ts

[Frontend] 예약 수정페이지 구현

---

client/src/App.tsx
client/src/components/Header/Header.tsx
client/src/components/Layout/HeaderLayout.tsx
client/src/pages/Register.tsx
client/src/pages/ReservationCheck.tsx
client/src/pages/StoreCheck.tsx
client/src/pages/StoreModify.tsx
client/src/pages/WishList.tsx

[fix] 헤더 에러 수정

---

client/.env
client/src/components/Home/Carousel.tsx
client/src/components/Home/KakaoMap.tsx
client/src/intefaces/Home.ts
client/src/pages/Home.tsx
client/src/store/homeAtom.ts
client/src/styles/Home/Carousel.tsx
client/src/styles/Home/Home.ts

[feat] 메인 페이지 완료

---

client/src/dummy/reservationcheckdummy.ts
client/src/pages/ReservationCheck.tsx
client/src/styles/MyPage/ReservationCheck.ts

[Frontend] 예약 내역 조회 페이지 UI 구현 완료

---

server/src/main/java/actiOn/auth/utils/StubDataLoader.java

- resolved #12
- resolved
화이팅!!!

(fix) 아이템 내용 수정

---

client/src/components/Partner/SelectBox.tsx
client/src/pages/Partner.tsx
client/src/styles/Partner/Partner.ts
client/src/styles/Partner/SelectBox.ts

[Frondend] 파트너 등록 페이지 기능구현

---

client/src/components/Partner/BusinessComponents.tsx
client/src/components/Partner/FormRegistration.tsx
client/src/components/Partner/RegistrationNumber.tsx
client/src/components/Partner/RepresentativeName.tsx
client/src/components/Partner/SelectBox.tsx
client/src/components/Partner/index.ts
client/src/pages/Partner.tsx

코드가 너무 길어서 컴포넌트로 나눠서 세분화시켜놨습니당

[Frondend] 파트너 등록 페이지

---

client/src/pages/Partner.tsx

API 연결까지 확인 후, 파트너 등록에 성공하면 /home 으로 이동, 파트너 등록에 실패하면 alert창 보여주기 기능까지 구현했습니다.

[Frontend] 파트너 등록페이지 api 연결 완료

---

server/src/main/java/actiOn/Img/profileImg/ProfileImg.java
server/src/main/java/actiOn/Img/profileImg/ProfileImgRepository.java
server/src/main/java/actiOn/Img/service/ImgService.java
server/src/main/java/actiOn/auth/dto/LoginResponseDto.java
server/src/main/java/actiOn/auth/handler/MemberAuthenticationSuccessHandler.java
server/src/main/java/actiOn/business/service/BusinessService.java
server/src/main/java/actiOn/member/controller/MemberController.java
server/src/main/java/actiOn/member/entity/Member.java
server/src/main/java/actiOn/member/mapper/MemberMapper.java
server/src/main/java/actiOn/member/service/MemberService.java

[Backend] 마이페이지, 로그인 기능 수정 및 리팩토링

---

client/src/components/CategoryDetail/DetailContent.tsx
client/src/components/CategoryDetail/PaymentInfo.tsx
client/src/components/CategoryDetail/Review.tsx
client/src/components/CategoryDetail/TicketCard.tsx
client/src/components/CategoryDetail/TicketSelect.tsx
client/src/components/StoreAdd/AddImages.tsx
client/src/components/StoreAdd/AddProduct.tsx
client/src/components/StoreAdd/Address.tsx
client/src/components/StoreAdd/StoreAddTop.tsx
client/src/pages/CategoryDetail.tsx
client/src/pages/StoreAdd.tsx
client/src/store/StoreAdd.ts
client/src/store/categoryDetailAtom.ts

[Frontend] 업체 등록 페이지 기능 구현 완료

---

client/src/pages/MyPage.tsx
client/src/styles/MyPage/MyPage.ts

[Frontend] 프로필 이미지 border, 사진 버튼들 수정

---

server/src/main/java/actiOn/Img/service/ImgService.java
server/src/main/java/actiOn/auth/oauth2/OAuth2MemberSuccessHandler.java
server/src/main/java/actiOn/config/sercurity/SecurityConfiguration.java

[Backend] oauth2 설정

---

server/src/main/java/actiOn/auth/oauth2/OAuth2MemberSuccessHandler.java

- resolved #12
- resolved
화이팅!!!

[chore] OAuth2 설정 추가

---

client/src/components/CategoryDetail/ReservationInfo.tsx
client/src/pages/Payments.tsx

[Frontend] 콘솔 로그 제거

---

client/src/pages/CategoryDetail.tsx
client/src/pages/Partner.tsx

- resolved #
- resolved
화이팅!!!

[test] 개발자 테스트 체크리스트

---

client/.env
client/src/components/Header/Header.tsx
client/src/pages/CategoryDetail.tsx
client/src/pages/CategoryPage.tsx
client/src/store/categoryAtom.ts

[fix]: 버그수정

---

client/src/components/MyPage/SideBar.tsx
client/src/pages/StoreCheck.tsx
client/src/styles/MyPage/StoreCheck.ts

[Frontend] 마이페이지(판매서비스관리) 기능 구현

---

server/src/main/java/actiOn/Img/service/ImgService.java
server/src/main/java/actiOn/config/S3Configuration.java
server/src/main/java/actiOn/store/controller/StoreController.java
server/src/main/resources/application.yml

[Backend] store 기능 수정

---

client/package-lock.json
client/package.json
client/src/components/Categorybar/CategoryCard.tsx
client/src/pages/MyPage.tsx
client/src/pages/WishList.tsx
client/src/styles/MyPage/WishList.ts

[Frontend] 마이페이지(위시리스트)

---

client/src/components/Header/Dropdown.tsx
client/src/components/Header/Header.tsx
client/src/pages/ReservationModify.tsx
client/src/router/MyRouter.tsx
client/src/styles/Category/CategoryPage.ts
client/src/styles/Header/Dropdown.ts
client/src/styles/Header/Haeder.ts
client/src/styles/Reservation/ReservationModify.ts

- resolved #25 
- 예약 수정페이지 기능구현
화이팅!!!

[Frontend] 예약수정페이지 기능구현

---

client/src/pages/ReservationCheck.tsx

- resolved #25
- resolved #44
화이팅!!!

[Frontend] 예약 조회 페이지 완료

---

client/src/components/Header/Searchbar.tsx
client/src/pages/ReservationModify.tsx
client/src/styles/Header/Searchbar.ts
client/src/styles/Login/Login.ts
client/src/styles/Register/Register.ts

- resolved #25 
- 오타 수정했습니다 !
화이팅!!!

[fix] 예약수정페이지 버그 수정 & UI 마진바텀 추가

---

client/src/pages/ReservationCheck.tsx

[Frontend] 예약 조회 버그 수정

---

client/.env
client/src/App.tsx
client/src/components/CategoryDetail/DetailContent.tsx
client/src/components/CategoryDetail/PaymentInfo.tsx
client/src/components/CategoryDetail/Review.tsx
client/src/components/CategoryDetail/TicketCard.tsx
client/src/components/Categorybar/CategoryCard.tsx
client/src/index.css
client/src/pages/CategoryDetail.tsx
client/src/pages/Home.tsx
client/src/pages/PaymentSuccess.tsx
client/src/pages/Payments.tsx
client/src/pages/StoreAdd.tsx
client/src/router/CategoryRouter.tsx
client/src/router/MainRouter.tsx
client/src/styles/CategoryDetail/DetailContent.ts

[Frontend] 결제 기능 구현 완료

---

client/.env
client/src/components/MyPage/BusinessSpaceSection.tsx
client/src/components/MyPage/ConfirmationModal.tsx
client/src/components/MyPage/Modal.tsx
client/src/components/MyPage/UserInfoSection.tsx
client/src/pages/MyPage.tsx
client/src/styles/MyPage/BusinessSpaceSection.ts
client/src/styles/MyPage/MyPage.ts
client/src/styles/MyPage/UserInfo.ts

[Frontend] 마이페이지(내 정보 관리)

---

client/src/components/CategoryDetail/DetailContent.tsx
client/src/components/CategoryDetail/PaymentInfo.tsx
client/src/components/Footer/Footer.tsx
client/src/pages/Home.tsx
client/src/pages/PaymentSuccess.tsx
client/src/styles/CategoryDetail/DetailContent.ts
client/src/styles/Footer/Footer.ts
client/src/styles/Login/Login.ts
client/src/styles/Partner/Partner.ts
client/src/styles/PaymentSuccess/AfterPayment.ts
client/src/styles/Register/Register.ts

[Frontend] 푸터 디자인 수정

---

client/.env
client/src/components/CategoryDetail/LocationInfo.tsx
client/src/components/Home/KakaoMap.tsx
client/src/components/IntroPage/Page1.tsx
client/src/components/StoreAdd/AddImages.tsx
client/src/components/StoreAdd/AddProduct.tsx
client/src/pages/ReservationCheck.tsx
client/src/pages/ReservationModify.tsx
client/src/pages/StoreAdd.tsx
client/src/styles/Reservation/ReservationModify.ts

[Frontend] 환불 기능 구현 완료

---

client/src/router/MyRouter.tsx
client/src/styles/MyPage/MyPage.ts

[Frontend] 마이페이지 미 로그인시 접근 불가 기능

---

client/src/pages/Partner.tsx

[Frontend] 파트너 등록 성곳 시 로그아웃 기능구현

---

client/src/router/MyRouter.tsx

[Frondend] 마이페이지 접근불가 수정

---

client/src/pages/Partner.tsx

[Frontend] 파트너 등록 버튼 클릭시 로그인페이지로 이동기능 구현

---

client/src/components/MyPage/ConfirmationModal.tsx
client/src/components/MyPage/Modal.tsx
client/src/pages/MyPage.tsx
client/src/styles/MyPage/BusinessSpaceSection.ts
client/src/styles/MyPage/Modal.ts
client/src/styles/MyPage/MyPage.ts
client/src/styles/MyPage/UserInfo.ts

[Frontend] 마이페이지 디자인 수정

---

client/src/components/Header/Dropdown.tsx
client/src/components/MyPage/ConfirmationModal.tsx
client/src/components/MyPage/Modal.tsx
client/src/pages/MyPage.tsx
client/src/router/MyRouter.tsx
client/src/styles/MyPage/ConfirmationModal.ts

- resolved #
- resolved
화이팅!!!

[Frontend] 마이페이지 수정

---

client/src/components/CategoryDetail/PaymentInfo.tsx
client/src/components/CategoryDetail/Review.tsx
client/src/components/CategoryDetail/ReviewCard.tsx
client/src/pages/PaymentSuccess.tsx
client/src/pages/Payments.tsx
client/src/pages/ReservationCheck.tsx
client/src/pages/ReservationModify.tsx
client/src/styles/Reservation/ReservationModify.ts

- resolved #25
- resolved #85
화이팅!!!

[Frontend] 예약 내역 조회, 수정 완료

---

client/src/components/MyPage/LoadingComponent.tsx
client/src/components/MyPage/ProfileImageSection.tsx
client/src/pages/MyPage.tsx
client/src/router/MyRouter.tsx

[Frontend] 마이페이지 프로필 사진 완료

---

client/src/components/Header/Header.tsx
client/src/components/Header/Searchbar.tsx
client/src/components/IntroPage/Page1.tsx
client/src/components/IntroPage/Page2.tsx
client/src/components/IntroPage/Page3.tsx
client/src/components/IntroPage/Page4.tsx
client/src/index.css

- resolved #139 
- a태그로 수정 완료했습니당
화이팅!!!

[Frontend] 웰컴페이지 버그 수정

---

client/.env
client/src/components/CategoryDetail/PaymentInfo.tsx

- 예약 form에서 연락처는 010 또는 011만 되도록 수정
화이팅!!!

[Frontend] 전화번호 010/011 처리 완료

---

server/src/main/java/actiOn/review/repository/ReviewRepository.java
server/src/main/java/actiOn/review/service/ReviewService.java

feat/be/payment payment merge (#150)

---

client/src/components/Partner/FormRegistration.tsx
client/src/components/Partner/RegistrationNumber.tsx
client/src/components/Partner/SelectBox.tsx
client/src/pages/Partner.tsx
client/src/styles/Partner/Partner.ts

[Frontend] 파트너등록페이지 중복확인 기능 구현

---

client/src/components/Partner/RegistrationNumber.tsx
client/src/pages/MyPage.tsx

[Frondend]마이페이지 렌더링 400에러 해결, 파트너등록 중복확인 부분 추가 수정

---

client/src/components/MyPage/BusinessSpaceSection.tsx
client/src/pages/ReservationCheck.tsx
client/src/pages/StoreCheck.tsx
client/src/pages/WishList.tsx
client/src/styles/MyPage/ReservationCheck.ts
client/src/styles/MyPage/WishList.ts

- resolved #
- resolved
화이팅!!!

[Frontend] 마이페이지 전체적으로 수정보완

---

client/src/pages/ReservationCheck.tsx

- resolved #
- resolved
화이팅!!!

[Frontend] 예약내역조회 이용완료시 리뷰작성 버튼

---

client/src/components/CategoryDetail/PaymentInfo.tsx
client/src/components/CategoryDetail/Review.tsx
client/src/pages/StoreAdd.tsx

[Frontend] 리뷰 에러코드에 따라 다른 alert

---

client/src/pages/StoreCheck.tsx

- resolved #
- resolved
화이팅!!!

[fix]delete요청 삭제

---

client/src/components/MyPage/Modal.tsx
client/src/components/Partner/RegistrationNumber.tsx
client/src/pages/MyPage.tsx
client/src/pages/Partner.tsx
client/src/pages/ReservationCheck.tsx

- resolved #
- resolved
화이팅!!!

[Frontend] console.log 삭제

---

client/src/pages/WishList.tsx
client/src/styles/MyPage/WishList.ts

[Frontend]위시리스트 스크롤 수정

---

server/src/main/java/actiOn/review/repository/ReviewRepository.java
server/src/main/java/actiOn/review/service/ReviewService.java

fix/be/dev reveiwCount 수정

---

client/src/pages/WishList.tsx
client/src/styles/MyPage/MyPage.ts
client/src/styles/MyPage/WishList.ts

- resolved #12
- resolved
화이팅!!!

[Frontend] 위시리스트 scroll 2차 수정

---

client/src/components/MyPage/Modal.tsx
client/src/pages/ReservationCheck.tsx
client/src/styles/MyPage/ReservationCheck.ts

[Frontend] 예약내역조회, 프로필 편집 중복부분 수정

---

server/src/main/java/actiOn/exception/ExceptionCode.java
server/src/main/java/actiOn/reservation/repository/ReservationRepository.java
server/src/main/java/actiOn/reservation/service/ReservationService.java
server/src/main/java/actiOn/review/entity/Review.java
server/src/main/java/actiOn/review/repository/ReviewRepository.java
server/src/main/java/actiOn/review/service/ReviewService.java

[Backend] 댓글 에러코드 수정

---

client/src/styles/MyPage/MyPage.ts

- resolved #22
- resolved
화이팅!!!

[Frontend] 마이페이지 프로필 사진 편집 수정

---

client/src/styles/MyPage/MyPage.ts

[Frontend]마이페이지 프로필 수정

---

client/src/pages/MyPage.tsx

[Frontend] 마이페이지 프로필 사진 코드 수정

---

client/src/pages/Register.tsx

[fix] 버그수정

---

client/src/components/Categorybar/CategoryCard.tsx

[Frontend] 평점 소수점

---

client/src/components/CategoryDetail/DetailContent.tsx
client/src/pages/StoreAdd.tsx

[Frontend] 업체 수정에서 이미지 최소 3장

---

client/src/pages/StoreAdd.tsx

[Frontend] 업체 수정 이미지 갯수 제한

---

client/src/components/MyPage/ProfileImageSection.tsx

- resolved #12
- resolved
화이팅!!!

[Frontend] 마이페이지 프로필 코드 재수정

---

client/src/components/MyPage/ProfileImageSection.tsx

[Frontend] 마이페이지 프로필 사진변경 코드 수정

---

client/src/components/StoreAdd/AddImages.tsx

[Frontend] 업체 수정 이미지 개수 제한

---

client/src/pages/Register.tsx

[Frontend] 회원가입 UI 수정

---

client/src/pages/MyPage.tsx

[Frontend] 마이페이지 프로필 사진 코드 재수정

---

client/src/components/MyPage/ProfileImageSection.tsx
client/src/pages/MyPage.tsx

[Frontend]마이페이지 프로필 사진 코드 재수정

---

client/src/pages/MyPage.tsx

[fix]마이페이지 프로필 사진 재 수정

---

client/src/components/MyPage/ProfileImageSection.tsx
client/src/pages/MyPage.tsx

[Frontend]마이페이지 이미지 부분 재수정

---

client/src/components/CategoryDetail/Review.tsx

[Frontend] 리뷰에러 처리

---

client/src/pages/MyPage.tsx

[Frontend] 마이페이지 콘솔 삭제

---

client/src/pages/Register.tsx

[Frontend] 회원가입 상태 form 통합
